Repository acm-ucr/saf-website, pull requests merged in 2024-03, with the labels that each got.

#138 events component implementation
  src/components/events/Event.jsx
  src/components/events/Events.jsx
Labels: events

#135 ripple above image
  src/components/home/Landing.jsx
Labels: ready for review

#145 changed
  src/components/home/SAF.jsx
Labels: ready for review, animation

#146 Add Time function to Calendar component
  src/components/calendar/Modal.jsx
Labels: ready for review, events

#147 Animate week component
  src/components/awareness-week/Week.jsx
Labels: ready for review, animation

#142 added images to a folder
  public/images/assets/AliHussain.webp
  public/images/assets/AnisaOza.webp
  public/images/assets/AparnaPetluri.webp
  public/images/assets/AyeshaPerera.webp
  public/images/assets/HarshitaaArunkumar.webp
  public/images/assets/HeiliShah .webp
  public/images/assets/KrinaShah.webp
  public/images/assets/MeghnaChunduru.webp
  public/images/assets/ParnikaNammi.webp
  public/images/assets/RiaRadtke.webp
  public/images/assets/RitiDesai.webp
  public/images/assets/RuthRapuri.webp
  public/images/assets/RuthieShenoy.webp
  public/images/assets/ShireenMehta.webp
  public/images/assets/ShriyaGore.webp
  public/images/assets/SiyaPanchal.webp
Labels: question, board

#158 Added embedded links to GetInvolved icons
  src/data/GetInvolved.js
Labels: ready for review

#161 Events Title
  src/app/events/page.js
  src/components/home/get-invloved/Circle.jsx
Labels: ready for review, events

#160 External Links
  src/components/home/get-invloved/Circle.jsx
Labels: address comments

#163 Responsive why join
  src/components/home/WhyJoin.jsx
  src/components/home/get-invloved/GetInvolved.jsx
Labels: ready for review

#166 added links to footer
  src/data/Footer.js
Labels: ready for review

#162 updated board members w/ photos
  public/images/assets/HeiliShah.webp
  src/components/board/Board.jsx
  src/data/Board.js
Labels: address comments, board, data

#159 animation
  src/components/Description.jsx
  src/data/Footer.js
Labels: ready for review

#182 rounded board member images
  src/components/board/Board.jsx
Labels: ready for review

#187 added end event in modal
  src/components/calendar/Modal.jsx
Labels: address comments

#191 animated join
  src/components/home/get-invloved/Circle.jsx
  src/components/home/get-invloved/GetInvolved.jsx
  src/data/GetInvolved.js
Labels: ready for review

#190 smoothen onhover transition
  src/components/Description.jsx
Labels: ready for review
