Repository acm-ucr/saf-website, pull requests merged in 2024-01, with the labels that each got.

#20 footer component attempted
  package-lock.json
  src/components/Footer.jsx
  src/data/Footer.js
Labels: home, ready for review

#26 add to WhyJoin
  src/components/home/WhyJoin.jsx
Labels: ready for review

#24 Photo Component #11
  src/components/Photo.jsx
Labels: help wanted, general

#22 Title Component
  public/svg/title.svg
  src/app/about/page.js
  src/components/Footer.jsx
  src/components/Title.jsx
Labels: ready for review

#25 Implement NavBar
  src/components/Navigation.jsx
  src/data/Nav.js
Labels: home, ready for review

#39 bullet points
  src/components/home/WhyJoin.jsx
Labels: address comments

#46 Trinh/getinvolved
  package-lock.json
  src/app/page.js
  src/components/home/get-invloved/Circle.jsx
  src/data/GetInvolved.js
Labels: ready for review

#41 week component implementation
  src/components/awareness-week/Week.jsx
  src/data/WeeklyEvents.js
Labels: ready for review, awareness-week

#43 404 component
  src/app/not-found.js
Labels: help wanted

#45 implement Landing
  public/svg/landing.svg
  src/components/home/Landing.jsx
Labels: home, ready for review

#44 Initial change to board comp, needs further change
  public/svg/board-mandala.svg
  src/components/board/Board.jsx
Labels: help wanted, board

#48 saf component
  src/components/home/SAF.jsx
Labels: ready for review, general

#42 Description
  src/app/about/page.js
  src/components/Description.jsx
Labels: ready for review

#61 mobile get involved implementation
  src/components/home/get-invloved/Circle.jsx
  src/components/home/get-invloved/GetInvolved.jsx
Labels: ready for review, general, responsive

#63 Mobile Response on SAF.jsx
  src/components/home/SAF.jsx
Labels: ready for review, responsive

#66 Fix navbar responsivness
  src/components/Navigation.jsx
Labels: ready for review, general, responsive

#64 WhyJoin Mobile Responsiveness
  src/components/home/WhyJoin.jsx
Labels: ready for review

#60 Arieen17/about mobile resp
  src/components/Photo.jsx
Labels: ready for review

#62 Banquet Page
  src/app/banquet/page.js
Labels: ready for review, banquet

#65 Culture-Show
  src/app/culture-show/page.js
Labels: ready for review, culture-show

#67 Nats26/board
  public/images/board/Ayesha.webp
  public/images/board/Chinmayi.webp
  public/images/board/Kishan.webp
  public/images/board/Riti.webp
  public/images/board/Ryan.webp
  public/images/board/Zuha.webp
  public/svg/board-mandala.svg
  src/app/board/page.js
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
  src/data/Board.js
Labels: help wanted, board
