Repository acm-ucr/saf-website, pull requests merged in 2024-02, with the labels that each got.

#78 Made Photo Smaller
  src/components/Photo.jsx
Labels: ready for review

#79 implemented the rest of the about page
  src/app/about/page.js
Labels: ready for review, general

#83 Arieen17/safanimation
  package-lock.json
  package.json
  src/components/board/Board.jsx
  src/components/home/SAF.jsx
Labels: ready for review

#81 Responsive Title
  public/svg/landing.svg
  src/components/Title.jsx
Labels: ready for review

#90 Mobile week
  src/components/awareness-week/Week.jsx
Labels: ready for review

#84 Implement Calendar
  public/images/banquet.png
  public/images/banquet.webp
  public/images/culture-show/culture-show2.png
  public/images/culture-show/culture-show2.webp
  src/app/banquet/page.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/CustomHeader.jsx
  src/components/calendar/CustomToolbar.jsx
  src/components/calendar/Modal.jsx
  src/components/calendar/index.css
  src/data/Carousel.js
Labels: ready for review, events

#101 responsive ripple
  src/components/home/SAF.jsx
Labels: ready for review

#104 hiding icons footer
  src/components/Footer.jsx
Labels: ready for review

#103 Dylan/remove comments week
  src/components/awareness-week/Week.jsx
Labels: ready for review

#106 implemented responsive board
  src/components/board/Board.jsx
  src/components/board/Boards.jsx
Labels: ready for review, board, responsive

#110 get involved responsive for ipad
  src/components/home/get-invloved/Circle.jsx
Labels: ready for review, general, responsive

#115 Implement Event Component
  src/components/events/Event.jsx
Labels: ready for review, events

#114 space between footer
  src/app/about/page.js
Labels: ready for review

#118 Shapes on Week
  src/components/awareness-week/Week.jsx
Labels: ready for review

#111 Sreeja pagireddy/hover
  src/app/banquet/page.js
Labels: ready for review

#100 banquet
  src/app/banquet/page.js
Labels: ready for review, banquet

#127 Reroute Lean More
  src/components/home/SAF.jsx
Labels: ready for review

#129 Dylan/animate title
  src/app/about/page.js
  src/components/Title.jsx
Labels: ready for review, animation

#131 Fixed Ipad responsivness and removed home from page
  src/components/Navigation.jsx
  src/data/Nav.js
Labels: ready for review, general, responsive

#132 adjusted carousel on mobile
  src/components/Carousel.jsx
Labels: ready for review, responsive

#133 Animated PhotoStrip Update
  src/components/home/PhotoStrip.jsx
Labels: ready for review
